### ISSUE TITLE
Add support to run cargo from CARGO_MANIFEST_DIR

### ISSUE THREAD

**Issue by sluedecke** [peterstuart/cargo-transient#32]
It turns out, cargo is run with the working dir set to the folder of the file I invoke cargo-transient from.  Most of the times this is `src`.

Since I access some files (`assets/foo.json` and similar) which are placed below CARGO_MANIFEST_DIR, cargo-transient fails to run the code.

**Comment by peterstuart** [comment]
This is an unintended side effect of https://github.com/peterstuart/cargo-transient/pull/30. It also causes issues where the compilation buffer can't find the source files referenced in error messages, since they're relative to the Cargo.toml file rather than the current file.

I'm not familiar with `CARGO_MANIFEST_DIR`, but I assume that is the directory that contains `Cargo.toml`? I think that running `cargo` from that directory makes sense, and will still work for @cedarbaum (see the initial discussion about this here: https://github.com/peterstuart/cargo-transient/pull/29).
